### PR TITLE
Allow unknown thermostats to work instead of failing silently.

### PR DESCRIPTION
**Pull request by JerryWorkman**
Allow unknown thermostats to work instead of failing silently.

Based on fork of 1.2

### CODE REVIEW

**Comment by craftyguy** [comment]
Great! Do you plan to rebase this to the master branch, or shall I?

**Comment by JerryWorkman** [comment]
I don't have the time now.

You have my blessings. I shouldn't take long and will make all of the Home
Assistant users happy.

**Comment by craftyguy** [comment]
Sounds good, I'll take a look at it then. Thanks for your help!

**Comment by craftyguy** [comment]
@JerryWorkman I didn't want to push to your master branch to update this PR, so I created a new branch and new PR (#38), and will close this one. You're still the author of one commit to that branch, so I would appreciate it if you could look it over before I merge it :)

Thanks for the help, I really appreciate it!

**Pull request closed without merging**
